### ISSUE TITLE
add ytdlp

### ISSUE THREAD

**Issue by rinrinx2** [Manssizz/CendrawasihLeech#2]
https://github.com/yt-dlp/yt-dlp#installation
ytdl not good slow

**Comment by Manssizz** [comment]
I think ytdl and ytdlp/ytdlc is same about speed. And few month ago ytdlp is really unstable. Let me check and try before switch to ytdlp

**Comment by rinrinx2** [comment]
You can try ytdl now very very slow.

**Comment by Manssizz** [comment]
already porting. just try.
